google/yamlfmt

- command/command.go
I deleted unnecessary `return err`.  
`factory.NewDefault()`  func doesn't have `err` returned value.
> delete unnecessary 'return err'

- README.md
- cmd/yamlfmt/main.go
- command/command.go
- engine/engine.go
- engine/errors.go
- engine/util.go
- formatters/basic/README.md
- formatters/basic/config.go
- formatters/basic/factory.go
- formatters/basic/formatter.go
- formatters/basic/formatter_test.go
- go.mod
- go.sum
Closes #3 
Using yaml.v2 was naive; unmarshalling into a map mangles the key order
and removes comments. Unmarshalling using yaml.v3's far more robust
yaml.Node type means we can preserve key order and comments. Added the
first unit tests for these specific cases, but more tests will need to
come imminently.
> Update to yaml.v3 and use yaml.Node

- .goreleaser.yaml
Forgot to adjust the `yamlfmt` command build to use the path to the
command; by default it looks for a main function in the root of the repo
which I don't have.
> ci: Fix main build path

- .goreleaser.yaml
- README.md
It was not entirely clear that this is a tool maintained only by
myself at the moment, and isn't currently a wider Google product. This
section of the docs is to level expectations at this very early stage of
the project.
> docs: clarify maintainer

- README.md
This section could get lost with usage instructions if it's at the
bottom, moving it to the top so it's more clear to new viewers.
> docs: move maintainers section higher in README

- cmd/yamlfmt/main.go
- command/command.go
closes #8 
This adds support for formatting yaml passed in from stdin. This enables
yaml to be piped in, and the formatted result will be output back to
stdout.
> command: add support for formatting from stdin

- formatters/basic/formatter.go
- formatters/basic/formatter_test.go
Closes #14 
Files with multiple documents are more common than I originally thought,
so it is best that I switch to Decode and Encode for this formatter that
will properly format all documents in multi-document files.
> basic: Support formatting multi-document files

- engine/engine.go
- formatters/basic/README.md
- formatters/basic/config.go
- formatters/basic/formatter.go
- formatters/basic/formatter_test.go
The yaml.v3 library Encoder does not include the --- at the start of
yaml files, however that is a pretty common pattern. Provide users the
option to include it if they would like.
> basic: add include_document_start

- .github/workflows/ci.yaml
- engine/engine.go
- engine/util.go
- internal/paths/paths.go
If there was more than one exclude path, then every path would always be
included due to an uncaught logic bug.
> engine: fix exclude path bug

- README.md
I totally forgot to add documentation for the new stdin support.
> docs: add documentation for stdin operation

- Makefile
- formatters/basic/factory.go
- formatters/basic/factory_test.go
closes #23 
Under a certain configuration, the default value for `basic.Config.Indent`
would be ignored. Adjust the way the `NewWithConfig` function works to
decode the map overtop of default config, which will preserve default
values for fields not found in the map.
> basic: respect formatter config defaults

- README.md
- formatters/basic/README.md
`indent` configuration option should be used instead of `indentation` as stated in the docs.
> chore: fix indent typo in configuration options

- README.md
- cmd/yamlfmt/main.go
closes #26 
Most command line utilities handle stdin with the `-` or `/dev/stdin`
argument. This PR changes the stdin operation detection from `-in` to
`-` or `/dev/stdin`. This detection is done manually to keep behaviour
consistent across platforms.
> feat: accept - or /dev/stdin instead of -in

- README.md
- cmd/yamlfmt/main.go
closes #29 
This PR adds a feature I originally intended for the first version but
forgot about until the opened issue. The tool now accepts a new flag
`-conf` and accepts a relative or absolute path to a config file. If the
flag is not present, it will fall back to the default config.
> feat: add ability to pass config path

- formatters/basic/README.md
- formatters/basic/config.go
- formatters/basic/factory.go
- formatters/basic/factory_test.go
- formatters/basic/formatter.go
- formatters/basic/formatter_test.go
- internal/hotfix/crlf.go
- internal/hotfix/crlf_test.go
- yamlfmt.go
Closes #34 
Added a configuration option for line endings, which is a feature that
needs to exist anyway. Also included temporary hotfix behaviour for CRLF
normalization while waiting for upstream fixes to get merged.
> fix: hotfix shim for CRLF behaviour

- formatters/basic/README.md
- formatters/basic/config.go
- formatters/basic/formatter.go
- formatters/basic/formatter_test.go
- go.mod
- go.sum
- internal/hotfix/unicode.go
- internal/hotfix/unicode_test.go
closes #38 
There is a major bug in yaml.v3 that makes it incapable of encoding
emojis. There has been an issue and PR open to fix it for a very long
time, but it has still gotten no attention. This PR adds a new hotfix
that will parse the literal `\U00000000` codepoint sequences that yaml.v3
produces and outputs the unicode encoding. It can be enabled with the
new `emoji_support` configuration value for the basic formatter.
Unfortunately, any scalar with an emoji will come out double quoted;
might be able to rectify this but it will be very nasty. Going to accept
that consequence for now to unblock this breakage.
This uses a library I made on my personal account in some spare time I had. https://github.com/RageCage64/go-utf8-codepoint-converter
> hotfix: add utf-8 parsint for emoji_support

- formatters/basic/features.go
- formatters/basic/formatter_test.go
- internal/hotfix/retain_line_break.go
I notice my PR for retaining line breaks got refactors. However the original [indentLen func](https://github.com/google/yamlfmt/blob/e05c99fbdf1d44bf9e2780f30fe040ad2274da19/formatters/basic/line_break.go#L62) got removed. It's required. Things got complicated when yaml contains literal multi-line string. If the indent is fixed 2, when it comes to multi-level indent string the format result will be wrong. So the `paddinger` always return the max padding for each line.
This PR fixes the refactor regression issue and explicitly add a test case.
> fix: line break format issue after refactor code

- command/command.go
Now I bundle the binary as a vscode extension. I use the stdin method to do the job and set the editor settings `formatOnSave` true. Each time saving the file, the format result will always insert a new line at the end, which is annoying.
So, this PR:
- don't append new line at the end and keep the content as it is
- default retain line breaks for readability since format itself is all about readability
> chore: better format defaults

- README.md
- command/command.go
- engine/engine.go
- formatters/basic/README.md
- formatters/basic/config.go
- formatters/basic/errors.go
- formatters/basic/factory.go
- formatters/basic/factory_test.go
- formatters/basic/features.go
- go.mod
- go.sum
- internal/hotfix/unicode.go
- yamlfmt.go
Closes #48 
Using the new `multilinediff` there needed to be two changes made:
* Needed to handle diffs using the count of differences found, since the new reporter always reports something
* Needed to recongize a line separation character at the engine level
This PR fixes the diff handling, which was relatively trivial. However, an oversight since the beginning is that diffs never took into account the line ending being used, and assumed `\n`. This needed to be rectified, and lead to something of a re-architecture that adds `line_ending` as a setting that acts as a global override. This required simplifying the `Factory` interface a little bit, in a way that sort of simplifies it. While refactoring anyway, I also decided to simplify the line break logic, so I didn't have to repeat the …
> feat: global linesep character, handle diffs

- cmd/yamlfmt/flags.go
I test the binary in windows today. When I pass the config file in cli args, it always join the current binary dir and the path like `c:\a\b.yaml` which result windows error: `The filename, directory name, or volume label syntax is incorrect.`
> fix: windows file path not right

- .gitignore
- internal/hotfix/unicode.go
- internal/hotfix/unicode_test.go
Closes #53 
Due to a logic oversight in the unicode parser, backslashes weren't being overwritten in scenarios where the backslash wasn't part of a unicode point representation. This PR changes it so the point is only parsed if it sees \ and U at once, otherwise writing the \ as normal.
> hotfix: stop unicode from removing backslashes

- engine/engine.go
- formatters/basic/README.md
- formatters/basic/config.go
- formatters/basic/factory.go
- formatters/basic/features.go
- formatters/basic/formatter.go
- internal/anchors/check.go
- internal/anchors/check_test.go
- yamlfmt.go
Fixes https://github.com/google/yamlfmt/issues/51
This is a fairly rough first attempt. It adds a "during action" to compliment the before- and after-actions, which operates on the parsed YAML node instead of raw bytes.
Let me know what you think.
> Support disallowing YAML anchors and aliases

- internal/paths/paths.go
- internal/paths/paths_test.go
Closes #57 
If a directory was named such that it matched the include pattern (in most circumstances, if it was named ending in `.yml`/`.yaml`) then yamlfmt would try to read it and format it which would fail because it's a directory. This PR adds a stat check to ignore all directories. Also adds tests for this package which did not previously exist.
> paths: do not include directories in formatting

- internal/paths/paths.go
Problem: if an exclude is prefixed with `./`, the `doublestar.Match(pattern, path)` method for matching returns false.
This patch cleans up the pattern before `Match` function and makes `./`-prefixed excludes possible.
Signed-off-by: Florian Bauer <florian@fsrv.xyz>
> fix: cleanup exclude patterns

- README.md
- cmd/yamlfmt/config.go
- cmd/yamlfmt/flags.go
- cmd/yamlfmt/main.go
Closes #67 
This PR improves the config file resolution to resolve things in priority order. It also includes support for config from a configuration home directory (i.e. `$XDG_CONFIG_HOME`, `$HOME/.config`, `%LOCALAPPDATA%`) so a user can override the default config system-wide.
Signed-off-by: braydonk <braydonk@google.com>
> cmd: add support for config home directory

- formatters/basic/config.go
- formatters/basic/features.go
- formatters/basic/formatter.go
- formatters/basic/formatter_test.go
- go.mod
- go.sum
Closes #63
Closes #69
Updates `github.com/braydonk/yaml` to `v0.4.0` to use the new options. Adjusts the `include_document_start` option to use the library instead of a hack feature, and adds `scan_folded_as_literal` option to allow preservation of newlines in folded-style block scalars.
> Update yaml v3 and use new options

- .pre-commit-hooks.yaml
Closes #58 
This PR adds a .pre-commit-hooks.yaml file so that it can integrate with the popular `pre-commit` tool.
> pre-commit: Add pre-commit support

- cmd/yamlfmt/config.go
Closes #80 
Accidentally included a print I was using for debugging that printed all arguments specified in the path.
> yamlfmt: remove a print I used for debugging

- .pre-commit-hooks.yaml
Since pre-commit passes filenames that it finds as positional arguments, running `yamlfmt .` would basically run on the whole directory every time it finds a yaml file. This new entry should work more like other hooks do.
> pre-commit: fixed bad idea for entry

- docs/config.md
- formatters/basic/config.go
- formatters/basic/formatter.go
- go.mod
- go.sum
Updates the yaml library and adds a new option for indentless arrays.
See https://github.com/braydonk/yaml/pull/13 for library changes.
Closes #87
> basic: add indentless_array option

- README.md
- cmd/yamlfmt/config.go
- cmd/yamlfmt/flags.go
- cmd/yamlfmt/main.go
- command/command.go
- docs/command-usage.md
- docs/config-file.md
- docs/paths.md
- docs/pre-commit.md
Closes #88 
This PR addresses all the gaps in CLI flags vs the `.yamlfmt` configuration file. All parts of the `yamlfmt` can now be adjusted entirely through command line flags.
This PR also adds a huge amount of documentation which has been sorely lacking in the past.
> cmd: configure all the things through CLI

- cmd/yamlfmt/config.go
- command/command.go
Fixes https://github.com/google/yamlfmt/issues/99 by introducing config constructors
Note that this is one way to fix the issue, alternatives can be considered too
Without any `.yamlfmt`, `yamlfmt` behaves as expected, here below with debug logs : 
```text
$ rm .yamlfmt
$ go run ./cmd/yamlfmt
{Extensions:[yaml yml] Include:[] Exclude:[] Doublestar:false LineEnding:lf FormatterConfig:0x14000120168}
{Type: FormatterSettings:map[]}
$ go run ./cmd/yamlfmt --formatter retain_line_breaks=true
{Extensions:[yaml yml] Include:[] Exclude:[] Doublestar:false LineEnding:lf FormatterConfig:0x14000118150}
{Type: FormatterSettings:map[retain_line_breaks:true]}
```
Same expected behavior when `.yamlfmt` contains no overrides : 
```text
$ cat .yamlfmt
formatter:
type: basic
$ go run ./cmd/yamlfmt …
```
> cmd: initialize config fields before use

- .github/workflows/ci.yaml
- .github/workflows/release.yaml
- .pre-commit-hooks.yaml
- README.md
- cmd/yamlfmt/config.go
- engine.go
- go.mod
- internal/collections/errors.go
- internal/collections/errors_test.go
- path_collector.go
Since I was only using one simple feature of go 1.20 and nothing unique from go 1.19, it did not really make any sense to require such a new version. Downgrading it will make it easier for pre-commit users or folks installing through `go install`.
Implemented an Errors collection type to replicate the errors.Join feature from go 1.20.
Fixed a small path matching issue for exclusions. Closes #97
> downgrade yamlfmt to go 1.18

- docs/config-file.md
- formatters/basic/config.go
- formatters/basic/factory_test.go
- formatters/basic/formatter.go
- formatters/basic/formatter_test.go
- go.mod
- go.sum
Fixes https://github.com/google/yamlfmt/issues/104 using https://github.com/braydonk/yaml/pull/16
Add an option to change the number of padding spaces between the yaml content and the first `#` of a line comment
Keeping 1 as the default value for backward compatibility, although using 2 would make sense as it would be compliant with `yamllint` default rules
Example of usage : 
```bash
$ cat comments.yaml
key: "value" # line comment
$ yamlfmt --formatter pad_line_comments=2 comments.yaml
$ cat comments.yaml
key: "value"  # line comment
```
Also remove unneeded entries from the go sum file
> formatter: add pad_line_comments option

- path_collector.go
- path_collector_test.go
Doublestar tests have been disabled for quite a long time and I honestly forget why they were. Regardless, they were missing some features to be properly robust anyway. This PR re-enables the tests and adds two test cases relevant to #97 that will be skipped individually for now.
> yamlfmt_test: re-enable and fix doublestar tests

- cmd/yamlfmt/config.go
- cmd/yamlfmt/flags.go
- command/command.go
- docs/config-file.md
- engine/consecutive_engine.go
Adds a new flag to continue formatting even if there are some invalid yaml files found. Suggested in #114
> yamlfmt: add continue_on_error flag

- .gitignore
`make build` generates this file
https://github.com/google/yamlfmt/blob/569994bdbd896057ca0d60f4efcdb3c8d180a362/Makefile#L2-L3
> chore: add gitignore for build file

- cmd/yamlfmt/flags.go
- cmd/yamlfmt/main.go
- command/command.go
- docs/command-usage.md
When I addressed to create asdf plugin, the way to ensure the version of the binary is not found.
This feature always helps me. So I added a simple flag to print the version.
https://github.com/kachick/asdf-yamlfmt
https://github.com/asdf-vm/asdf-plugins/pull/829
> feat: add flag to print version

- docs/paths.md
- path_collector.go
- path_collector_test.go
Due to a misunderstanding on my part, I swapped standard filepath collection mode to calculate exclusions using absolute paths. This worked because of the way tests were written, but it does not work in most real world scenarios and it slipped by. I will be able to catch this better when I implement proper integration testing.
This PR removes the absolute paths from the calculation, and adds a doc entry to recommend that paths are always specified relative to the command working directory.
Closes #121 (exclude paths bug)
Closes #97 (doc change to suggest that paths are generally specified relative to command working directory)
> yamlfmt: fix standard mode exclude bug

- .goreleaser.yaml
`archives.replacements` was removed in a newer `goreleaser` version so I have to do this name template stuff :sob:
> goreleaser: replacements is deprecated

- command/command.go
Fixed a bug that the diffs were not displayed when running dry run even if FileDiffs existed.
In [this PR](https://github.com/google/yamlfmt/pull/90), quiet mode has been added
When running DryRun, messages will not be returned except in quiet mode
https://github.com/google/yamlfmt/pull/90/files#diff-9a5c609cc998c3fec5e5e127bbb7b37c8059b50713b6c2686344d43176b999d9R63-R77
In a subsequent PR, if there is no message, it has been changed so that the differences will not be output to stdout during DryRun
https://github.com/google/yamlfmt/pull/106/files#diff-9411b7c0f7187e3e94ff7f48851c1d31db3607a56078f9aa6bb1ae80121efbcfR146-R150
However, when you run dry-run, you should expect to see the differences.
> cmd: fixed to display dry-run outputs.

- docs/config-file.md
Closes https://github.com/google/yamlfmt/issues/141
> Docs: yaml to linked gopkg.in/yaml.v3 

- docs/pre-commit.md
`pre-commit` allows you to override any settings for hooks in your personal config. This override is useful to document here, since it will allow users to use a yamlfmt binary on their system instead of being forced into building it with Go for the purpose of the hook.
> docs: language system pre-commit override

- cmd/yamlfmt/config.go
- cmd/yamlfmt/flags.go
- cmd/yamlfmt/main.go
- docs/command-usage.md
- docs/config-file.md
Config discovery is changing, but it should be non-breaking.
* The search for a config now starts at the root directory and then searches up the tree to finding the lowest level one. This should help in larger monorepo setups when you want different configs in different places, or to fall back to some default higher in the tree. I am not 100% sure whether this will break some workflows but it will be pretty easy to either change back or provide a short-circuit if necessary.
* Added a new flag `-global_conf` that will force the usage of the config from `XDG_CONFIG_HOME`/`LOCALAPPDATA`
* The yamlfmt config can now be in `yamlfmt.yaml` or `yamlfmt.yml` instead of just `.yamlfmt`
> New config discovery procedure

- Makefile
- cmd/yamlfmt/config.go
- cmd/yamlfmt/flags.go
- cmd/yamlfmt/main.go
- docs/command-usage.md
- integrationtest/command/command_test.go
- integrationtest/command/testcase.go
- integrationtest/command/testdata/include_document_start/after/x.yaml
- integrationtest/command/testdata/include_document_start/before/x.yaml
- integrationtest/command/testdata/path_arg/before/x.yaml
- internal/collections/set.go
- internal/logger/debug.go
- internal/tempfile/golden.go
- path_collector.go
This PR adds debug logging. Debug logging can be enabled through flags to the yamlfmt command, and will tell you in very noisy detail about things that are going on. Debug groups are separated into codes, so that only certain debug logs can be enabled if you are debugging a specific problem.
I also fixed a bug I introduced in the last config PR with the `-conf` flag. It is fixed before ever going out in a release, so it will only affect someone who installed from that exact commit before I fix it here.
> Debug logging

- docs/config-file.md
- formatters/basic/config.go
- formatters/basic/features.go
- formatters/basic/formatter_test.go
- internal/hotfix/retain_line_break.go
Closes #152 
This PR adds a new formatter config option `retain_line_breaks_single` which will retain line breaks, but in large groups of line breaks only keep one at a time. So this:
```yaml
a: 1
b: 1
```
Becomes:
```yaml
a: 1
b: 1
```
> Retain single line breaks

- cmd/yamlfmt/config.go
Based on the line in the docs:
> If the flag -global_conf is passed, all other steps will be circumvented and the config file will be discovered from the system config directory
This logic was backwards. Current functionality searches for the `-conf` path and when one isn't passed (like when using `-global_conf` only) it immediately returns and does not search for the global_conf. This causes the config file from the current working directory to be picked up _before_ the global conf does even when the flag is set explicitly.
Examples A, C, D are given so that existing & future functionality can be shown to be the same. However Example B is the current and fixed issue.
- Config exists in local directory
- Global config exists
- No flags passed in
Expected result: Uses local config
Existing …
> Fix: global_conf not taking priority

- cmd/yamlfmt/config.go
- docs/config-file.md
Closes #160 
This PR allows for the yamlfmt config file to be hidden if it has an extension.
> yamlfmt: hidden version of config file with ext

- .github/workflows/ci.yaml
- .github/workflows/release.yaml
- .pre-commit-hooks.yaml
- Makefile
- cmd/yamlfmt/config.go
- content_analyzer.go
- content_analyzer_test.go
- engine.go
- engine/output.go
- formatter.go
- formatters/basic/errors.go
- integrationtest/command/command_test.go
- integrationtest/command/testcase.go
- internal/assert/assert.go
- internal/assert/assert_test.go
- internal/collections/errors.go
- internal/collections/errors_test.go
- internal/collections/set.go
- internal/collections/slice.go
- internal/logger/debug.go
- internal/multilinediff/multilinediff.go
- internal/tempfile/golden.go
- internal/tempfile/path.go
- linebreak.go
- metadata.go
- metadata_test.go
- path_collector.go
- path_collector_test.go
I have been neglecting to add license headers for a while. Added a check in CI so I stop forgetting.
> Add license headers

- command/command.go
When I added output format, I accidentally changed a string cast for the stdin operation's output which I should have left.
Will add an integration test to cover this but I'm getting this through first so I can patch release.
> command: fix stdin operation output

- .github/workflows/release.yaml
- .goreleaser.yaml
- Makefile
- cmd/yamlfmt/main.go
Suggestion
---
I want to resolve two things in this PR.
* Fill revision with git ref
* Prevent missing to bump the version string
Background
---
https://github.com/google/yamlfmt/releases/tag/v0.12.1
* >Known Issue: I was in a rush to get this out when I saw it and forgot to manually update the version string, so yamlfmt -version will print v0.12.0 for this version.
* https://github.com/google/yamlfmt/pull/175
* https://github.com/google/yamlfmt/pull/178
This is my omitted part in https://github.com/google/yamlfmt/pull/117 🙇‍♂️ 
Example
---
goreleaser
```console
> goreleaser build --single-target --snapshot --clean
> ./dist/yamlfmt_linux_amd64_v1/yamlfmt --version
0.12.2-next
```
go build / go install
```console
> make build
> ./dist/yamlfmt -version
0.12.0
```
goreleaser
```console
> …
```
> feat: fill version with git and ldflags

- .github/workflows/ci.yaml
Currently go vet does not check many files, for example `cmd/*.go`
```console
> go version
go version go1.22.2 linux/amd64
> go vet -json
{}
{}
> go vet -json ./...
{}
{}
{}
{}
{}
{}
{}
{}
{}
{}
{}
{}
{}
{}
{}
{}
{}
```
> chore(ci): fix missing targets when using `go vet`

- docs/config-file.md
- formatters/basic/config.go
- formatters/basic/features.go
- formatters/basic/formatter_test.go
- integrationtest/command/command_test.go
- integrationtest/command/testdata/eof_newline/after/a.yaml
- integrationtest/command/testdata/eof_newline/before/a.yaml
- integrationtest/command/testdata/print_conf_file/stdout/stdout.txt
- integrationtest/command/testdata/print_conf_flags/stdout/stdout.txt
- integrationtest/command/testdata/print_conf_flags_and_file/stdout/stdout.txt
- internal/features/eof_newline.go
- internal/features/trim_whitespace.go
This PR adds a new option to forcibly add the end of file newline if it's not there. This is useful in the scenario where the `retain_line_breaks` feature is disabled but the eof newline is still wanted.
> Add eof_newline option

- schema.json
Docs:
- https://github.com/google/yamlfmt/blob/main/docs/config-file.md
- https://json-schema.org/
- https://json-schema.org/learn/getting-started-step-by-step#create-a-schema-definition
Issue #181
> feat: introduce a json schema file for yamlfmt

- internal/features/eof_newline.go
This PR resolves #196.
YAMLfmt throws panic when linting an empty file with eof_newline feature on.
The problem is that `eofNewlineFeature` has out-of-range access when `content` is empty.
This PR fixes it and handles case when `content` is empty.
> 🐛 panic against empty file with eof_newline feature, resolves: #196

- path_collector.go
Currently `yamlfmt` fails if the gitignore file is not found in the current directory. This is not desirable as sometimes we may work in sub-directories of a repo.
This PR looks for the gitignore file until the root of repo and fails if not found (and eventually until the root of the filesystem if no gitdir is found).
Closes #199
> fix: look for gitignore file until the git root

- .github/workflows/release.yaml
- .goreleaser.yaml
- README.md
- go.mod
- go.sum
Hi. Thanks for maintaining `yamlfmt`!
I saw that the release artifacts aren't being signed. This PR adds the ability to sign the checksum file using [cosign keyless signing](https://docs.sigstore.dev/signing/signing_with_blobs). It's all done via goreleaser (which is also upgraded to [version 2](https://goreleaser.com/blog/goreleaser-v2/)).
**You can see this running in action [here](https://github.com/dhth/yamlfmt/pull/1).**
*Not sure if signing release assets was on your roadmap, but if it was, hopefully this helps :)*
---
I've also added instructions on how to verify the authenticity of the released assets to the README. Basically, the process looks like this (this is tweaked for my fork):
1. Download the following files from the release:
```text
curl -sfLO …
```
> ci: sign checksum file with cosign

- docs/output.md
- engine/output.go
- integrationtest/command/command_test.go
- integrationtest/command/testdata/gitlab_output/after/correctly_formatted.yaml
- integrationtest/command/testdata/gitlab_output/after/needs_format.yaml
- integrationtest/command/testdata/gitlab_output/before/correctly_formatted.yaml
- integrationtest/command/testdata/gitlab_output/before/needs_format.yaml
- integrationtest/command/testdata/gitlab_output/stdout/stdout.txt
- internal/gitlab/codequality.go
- internal/gitlab/codequality_test.go
This adds a new output format, `gitlab`, which produces [Code Quality reports](https://docs.gitlab.com/ee/ci/testing/code_quality.html#code-quality-report-format) for GitLab. This allows GitLab CI jobs to annotate which files need formatting. Without this, a CI job can only fail, leaving the user to sieve through the logs to find out which files they need to format.
Example output:
```json
[
{
"description": "Not formatted correctly, run yamlfmt to resolve.",
"check_name": "yamlfmt",
"fingerprint": "c1dddeed9a8423b815cef59434fe3dea90d946016c8f71ecbd7eb46c528c0179",
"severity": "major",
"location": {
"path": ".golangci.yaml"
}
}
]
```
> output: Add the `gitlab` output.

- docs/paths.md
- path_collector.go
- path_collector_test.go
I want to format templated YAML files, which have file names like `config.yaml.gotmpl`. We also have other files, such as `README.md.gotmpl` which we do *not* want to format with yamlfmt.
Previously, yamlfmt used `strings.Split()` to extract the extension from a file. This doesn't work when the extension itself contains a dot.
With this change, yamlfmt uses `strings.HasSuffix()` to match files instead, allowing to match multi-part extensions.
That said, I'll probably end up using the "doublestar" implementation – I just didn't understand what it does before reading the code. If you end up grabbing the doc update only, I'd be happy too.
For my purposes, I'd actually love to have a single file to list includes *and* excludes. The "Git ignore" syntax allows you to do this, for example: …
> Extensions

- .github/workflows/release.yaml
- .pre-commit-hooks.yaml
- docs/config-file.md
- schema.json
According to the article https://go.dev/doc/faq#go_or_golang:
> The language is called Go. The “golang” moniker arose because the web site was originally golang.org. (There was no .dev domain then.) Many use the golang name, though, and it is handy as a label. For instance, the social media tag for the language is “#golang”. The language’s name is just plain Go, regardless.
> docs: change the language name from `Golang` to `Go`

- command/command_test.go
- internal/assert/assert.go
- internal/assert/assert_test.go
The PR corrects grammar mistakes in tests.
> fix typos in test names

- .github/workflows/release.yaml
- Dockerfile
- README.md
See https://github.com/google/yamlfmt/issues/229 for reference
> fix: add configuration for building container images

- docs/config-file.md
- formatters/basic/config.go
- formatters/basic/formatter.go
- formatters/basic/formatter_test.go
- integrationtest/command/testdata/print_conf_file/stdout/stdout.txt
- integrationtest/command/testdata/print_conf_flags/stdout/stdout.txt
- integrationtest/command/testdata/print_conf_flags_and_file/stdout/stdout.txt
Fixes #237 
This PR makes use of the new functionality in the yaml library to allow alternate array indents and indenting the root array.
> add array indent functionality

- go.mod
- go.sum
- integrationtest/command/testdata/gitlab_output/after/correctly_formatted.yaml
- integrationtest/command/testdata/gitlab_output/before/correctly_formatted.yaml
Updates yaml library to v0.9.0. This includes https://github.com/braydonk/yaml/pull/21
Fixes #236 and #147
> update yaml to v0.9.0

- docs/config-file.md
- formatters/basic/config.go
- formatters/basic/formatter.go
- integrationtest/command/command_test.go
- integrationtest/command/testdata/alias_key_correction/after/x.yaml
- integrationtest/command/testdata/alias_key_correction/before/x.yaml
- integrationtest/command/testdata/print_conf_file/stdout/stdout.txt
- integrationtest/command/testdata/print_conf_flags/stdout/stdout.txt
- integrationtest/command/testdata/print_conf_flags_and_file/stdout/stdout.txt
- pkg/yaml/apic.go
- pkg/yaml/emitterc.go
- pkg/yaml/formattest/encode_test.go
- pkg/yaml/formattest/testcase.go
- pkg/yaml/formattest/testdata/alias_key/expected.yaml
- pkg/yaml/formattest/testdata/alias_key/input.yaml
- pkg/yaml/yaml.go
- pkg/yaml/yamlh.go
As outlined in #247, the yaml library did not initially handle this edge case of using an alias node as a key properly. This PR adds functionality to correct that. In case there is some other edge case where this breaks, the `disable_alias_key_correction` formatter config option was added.
> pkg/yaml: correct alias keys

- docs/pre-commit.md
> docs(pre-commit): bump yamlfmt version

- formatters/basic/formatter.go
- formatters/basic/formatter_test.go
Fixes #254 
When `yaml.v3` parses a document that's just comments, it ends up parsing no actual nodes and thus loses the comment information. This will now be treated as an edge case and return the original content, in essence not modifying it if the yaml parsed successfully but no nodes are parsed out.
> formatters/basic: fix just comments edge case

- pkg/yaml/emitterc.go
- pkg/yaml/formattest/testcase.go
- pkg/yaml/formattest/testdata/alias_key/expected.yaml
- pkg/yaml/formattest/testdata/alias_key/input.yaml
PR #247 introduced a regression with YAML documents such as this:
```yaml
config: &shared
key: value
instance:
<<: *shared
```
Due to the "correct alias keys" setting, a extra space was emitted after `*shared`. This created trailing whitespace which many tools (rightly) complain about.
This change adds an extra condition to only emit the space in the "simple key" context. I'm not enough of a YAML expert to be sure this is the right thing to do, but it fixes my problem without failing any of the existing tests.
> Remove trailing whitespace from merge aliases.
