google/yamlfmt

- .gitignore
- .goreleaser.yaml
Part of #2 
Add goreleaser configuration for releasing. Will do releases manually
for now, and create an automated process for it when I have the time to
do it properly.
> ci: Add goreleaser

- .github/workflows/ci.yaml
- .goreleaser.yaml
- Makefile
- engine/engine.go
- engine/errors.go
- internal/diff/diff.go
- internal/diff/diff_test.go
- internal/diff/reporter.go
closes #7 
By implementing a custom diff reporter, this will improve diff
readability. It's still not perfect, but it's not extremely ugly like
before.
> diff: improve diff readability

- cmd/yamlfmt/flags.go
- cmd/yamlfmt/main.go
This PR will improve the help message for the command. It also moves the
flag definitions to a separate file, since the flag functionality is
likely to increase in complexity.
> feat: improve help message

- formatters/basic/README.md
- formatters/basic/config.go
- formatters/basic/errors.go
- formatters/basic/formatter.go
- go.mod
- go.sum
Closes #39 
This adds the option to set max line length in the basic formatter.
> basic: allow for setting line length

- docs/config.md
I should've documented that lol
> Document scan_folded_as_literal option

- README.md
Closes #58 
This PR documents the pre-commit installation instructions. Do not merge this PR til v0.8.0
> README: document pre-commit

- docs/config.md
> docs: fix config field typo

- README.md
Correct config file document path
> Correct config file document path

- formatters/basic/formatter.go
It may not be something worth going out of your way to correct, but...
> docs: fix typo comment

- content_analyzer_test.go
> chore: fix a typo

- engine.go
Closes #163 
This PR changes file diff application to not write the file if it wasn't changed.
> yamlfmt: don't write diff if not changed

- .github/workflows/release.yaml
https://github.com/goreleaser/goreleaser/blob/15a0c54f61390bd95acbd99577aa240d64a2d18c/www/docs/deprecations.md?plain=1#L235
> change deprecated goreleaser flag

- schema.json
> fix(json schema): remove additionalProperties any

- go.mod
- go.sum
- internal/jsonschema/schema_test.go
This PR adds barebones JSON schema compile test to catch future issues like #202 in CI.
> Add JSON schema validity test

- README.md
> Clarify that cosign support will only be present starting from v0.14.0

- .github/workflows/release.yaml
idk it's giving a 403 maybe I need v2 of this
> This might fix releases

- .github/workflows/release.yaml
I hate writing CICD I should never be in charge of this
> why did this used to work but not anymore

- docs/pre-commit.md
> Update pre-commit.md to use latest release

- formatters/basic/README.md
Just updating a broken link -(and love the tool!)
> fix: correct link to configuration docs

- go.mod
- go.sum
This update brings in:
* https://github.com/braydonk/yaml/pull/18
* https://github.com/braydonk/yaml/pull/19
* https://github.com/braydonk/yaml/pull/20
> update yaml package
